version: '3'
services:
  mapgen-frontend:
    build:
      context: .
      dockerfile: ./container/frontend/Dockerfile
    image: ghcr.io/xcsoar/mapgen-frontend
    ports:
      - "9090:9090"
    volumes:
      - mapgen-jobs:/opt/mapgen/jobs
      - ./lib:/opt/mapgen/lib
      - ./bin:/opt/mapgen/bin
  mapgen-worker:
    build:
      context: .
      dockerfile: ./container/worker/Dockerfile
    image: ghcr.io/xcsoar/mapgen-worker
    volumes:
      - mapgen-jobs:/opt/mapgen/jobs
      - mapgen-data:/opt/mapgen/data
      - ./lib:/opt/mapgen/lib
      - ./bin:/opt/mapgen/bin

volumes:
  mapgen-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/bapt/.xcsoar_mapgen/mapgen-data
  mapgen-jobs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bapt/.xcsoar_mapgen/mapgen-jobs
